 name: Deploy to Deno Deploy
 
 on:
   push:
     branches: ["main"]
   workflow_dispatch:
 
 permissions:
   id-token: write
   contents: read
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Setup Deno
         uses: denoland/setup-deno@v2
         with:
           deno-version: v2.x
 
       - name: Deploy to Deno Deploy
         uses: denoland/deployctl@v1
         with:
           project: "strong-stoat-61"
           entrypoint: "main.ts"
